### ISSUE TITLE
ENH: repace general Exception with specific exceptions

### ISSUE THREAD

**Issue by aburrell** [KCollins/conjugate-map#16]
# Description
Allowing any failure to be caught in a try/except loop can create unidentified bugs.

## Potential impact

- Is the feature related to an existing problem?  There are several try/except loops with generic catches
- How critical is this feature to your workflow?  This will allow for unexpected behaviour, especially if dependencies change
- How wide of an impact to you anticipate this enhancement having?  Essential for maintenance, potentially hides existing bugs
- Would this break any existing functionality? No

## Potential solution(s)
Specify allowed exceptions when possible

# Alternatives
Leave as is

# Additional context
This will likely be cleared up when linting tests pass.

**Comment by KCollins** [comment]
Related to Issue #4 - lint doesn't like the current approach.

**Comment by KCollins** [comment]
Closed in most recent commit.
