### ISSUE TITLE
ENH: create documentation

### ISSUE THREAD

**Issue by aburrell** [KCollins/conjugate-map#6]
Create documentation and publish it on a site like readthedocs.

- [X] create a `docs` directory for the documentation
- [X] add installation instructions
- [X] add citation instructions
- [x] create an API from the docstrings
- [X] add usage examples
- [X] provide a link to the notebooks
- [X] publish online

**Comment by KCollins** [comment]
Started this process at https://readthedocs.org/projects/conjugate-map/

**Comment by KCollins** [comment]
Documentation is merged into /develop branch. I think we have everything except for the API documentation... 
I found this (https://www.sphinx-doc.org/en/master/man/sphinx-apidoc.html) but I don't quite understand how that part works.
