### ISSUE TITLE
MAINT: update notebooks

### ISSUE THREAD

**Issue by aburrell** [KCollins/conjugate-map#8]
Update notebooks to account for package refactoring.

**Comment by KCollins** [comment]
`from conjugate_map.conjCalcFunctions import *` seems to work in my local copy. Is that syntax correct?

**Comment by aburrell** [comment]
It will work, but because it will overwrite stuff that you may not intend it is highly discouraged.  If you want to import everything, it's better practice to do something like:

```
import conjugate_map.conjCalcFunctions as calc_funcs

output = calc_funcs.function_to_do_something(inputs)
```
